name = "Aden's Mod Shed"
author = "Aden"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9944d6cef9eb77f445f12ca10a6425d13c7e4f70cee90b576b08a85a541b0c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
