name = "Aden's Mod Shed"
author = "Aden"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c398d1bbbde5d6a1c762d206da5ab20a21654202097dacda4cdd709cbf97f7d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
